refactor: Restructure tests into api, components, e2e suites (#5)
* Initial project : Playwright, pnpm, TS, eslint, .env

* feat: Implement login smoke test with POM and fixtures

* feat: Add positive login flow test using Cognito Page Object

* feat: Add API test for IAM health check endpoint

* refactor: Restructure tests into api, components, e2e suites

---------

Co-authored-by: Mykhailo Hural <mykhailo_hural@epam.com>

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,27 +1,71 @@
 name: Playwright Tests
+
 on:
   push:
     branches: [ main, master ]
   pull_request:
     branches: [ main, master ]
+  workflow_dispatch:
+    inputs:
+      test_suite:
+        description: 'Select the test suite to run'
+        required: true
+        default: 'all'
+        type: choice
+        options:
+          - all
+          - api
+          - components
+          - e2e
+
 jobs:
   test:
     timeout-minutes: 60
     runs-on: ubuntu-latest
+
     steps:
-    - uses: actions/checkout@v4
-    - uses: actions/setup-node@v4
-      with:
-        node-version: lts/*
-    - name: Install dependencies
-      run: npm install -g pnpm && pnpm install
-    - name: Install Playwright Browsers
-      run: pnpm exec playwright install --with-deps
-    - name: Run Playwright tests
-      run: pnpm exec playwright test
-    - uses: actions/upload-artifact@v4
-      if: ${{ !cancelled() }}
-      with:
-        name: playwright-report
-        path: playwright-report/
-        retention-days: 30
+      - uses: actions/checkout@v4
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: lts/*
+
+      - name: Install dependencies
+        run: npm install -g pnpm && pnpm install
+
+      - name: Install Playwright Browsers
+        run: pnpm exec playwright install --with-deps
+
+      - name: Run Playwright tests
+        if: github.event_name == 'pull_request' || github.event_name == 'push'
+        run: pnpm test
+
+      - name: Run selected tests manually
+        if: github.event_name == 'workflow_dispatch'
+        run: |
+          SELECTED="${{ github.event.inputs.test_suite }}"
+
+          if [[ "$SELECTED" == "all" ]]; then
+            echo "▶ Running ALL tests"
+            pnpm exec playwright test
+            exit $?
+          fi
+
+          TEST_DIR="src/tests/$SELECTED"
+
+          if [[ -d "$TEST_DIR" ]]; then
+            echo "▶ Running test suite: $SELECTED"
+            pnpm exec playwright test "$TEST_DIR"
+          else
+            echo "ERROR: Test suite \"$SELECTED\" not found."
+            echo "Checked path: $TEST_DIR"
+            exit 1
+          fi
+
+      - name: Upload Report
+        uses: actions/upload-artifact@v4
+        if: always()
+        with:
+          name: playwright-report
+          path: playwright-report/
+          retention-days: 30
